apiVersion: v1
kind: Service
metadata:
  name: go-microservice-service
spec:
  selector:
    app: go-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
